# Python Basics  

* 這份檔案以DataCamp的第一章：Introduction to Python為主軸做整理，並補充一些後續看到的內容  

## Variable and Types  

* python有以下幾種types:  
  * int: 整數  
  * float: 就numeric  
  * str: string  
  * bool: boolean (True, False)  
* 檢查變數的type，就用  

```{python}
desc = "compound interest"
print(type(desc))
```
* 轉換型別：  
  * 轉成字串用`str()`： 通常是把數字轉成字串，用於製造出包含數字的字串句子    
  * 轉成整數用`int()`, 轉成數字用`float()`: 通常都是把文字轉成數字  
  
```{python}
str1 = str(1000)
print(str1)
print(type(str1))
```

```{python}
str2 = "5566"
int2 = int(str2)
print(int2)
print(type(int2))
```
## Operations  

* 數字的型別，當然可以做加減乘除  
* 那文字的呢？  
* 那Boolean的呢？  

### 字串的operations  

#### 想paste字串，直接用+  

```{python}
"Let me" + " see see"
```

## Methods  

* 在python裡，所有東西都是object  
* 每個object都有所屬的method，可以想成此object的專屬技能(Methods: Functions that belong to objects)  
* 至於是什麼method呢？depend on type!  
* 舉例來說，`a = "hahaha"`，那a是一個object，哪種type的object? string這種type的object，所以他有string的專屬技能。例如`a.upper()`可以把字串轉成全大寫  

### 字串的methods  

* 試試看改這個就好

#### .upper() 把字串全轉成大寫  

```{python}
a = "hahaha"
new = a.upper()
print(new)
print(a)
```

#### .capitalize() 把字首改大寫  

```{python}
a = "hahaha"
new = a.capitalize()
print(new)
print(a)
```

#### .count() 可以算某個字母出現幾次  

```{python}
a = "hahaha"
new = a.count("a")
print(new)
print(a)
```

## packages:  

* python的package就和R的package一樣，他就是一個資料夾，裡面放滿一個又一個的 .py script  
* 每個script，就是一個module，裡面specify functions, methods, types  
* 現在有成千上萬個python的package，例如numpy, scikit-learn...  

### Install package  

* 在terminal裡打`pip install numpy`

### Import package  

* `import numpy`  
* `import numpy as np`  
* `from numpy import array`: 只import numpy裡面的array這個function  
* `from numpy import *`: 這是最爛的寫法，他的意思是，我把numpy裡面所有的屬性和方法都load到我現在的environment裡面。爛的地方在於，他可以覆蓋掉你之前定義過的東西。例如，你之前定義過一個function叫`demo`，而numpy裡面也有一個function叫`demo`，那你一用`from numpy import *`，那現在的local environment就只剩numpy的demo了。   
* 整體來說，建議多用第二點，因為這樣當你用`array()`這個function時，會寫成`np.array()`，就會非常清楚這個function來自哪個package，而不會搞亂  
* 而對於引用自己寫好的local package，則較常使用from...import...這種寫法。詳情等module & package那個章節就知道  




## Methods  

* 別忘了，每種type他其實都是一種class，所以除了你定義好的資料外，他還有專屬技能(method)  
* 當我們把list的資料part，用上面教過的方法定義好後，接下來就可以用他的method，來對這個list工作  
* methods很容易讓人搞混的地方，是他做完事後會分成兩種狀況：1. 直接改變原object, 不吐新東西出來(吐None) 2. 不改變原object，但會吐新東西出來  
* 直接看例子：  

### list.append(x) = R的c(list, x)  

```{python}
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
new = fruits.append("grape")
print(new)
print(fruits)
```

* 從上例可以清楚的看到，當你用list.append時，他吐出來的值是None，而原list已經被改變了，這就是上面提過的狀況1  
* 要判斷一個method，他會是狀況1 or 狀況，有幾種方法：  
  1. 先猜: 做這個method，本質上就是要去改原物件的，那通常Python就會直接幫你改，例如這邊的.append就是    
  2. 做實驗驗證：總是先把結果存到一個新變數(如這邊的new)，然後看看new會不會是None，來做確認  
  3. 乖乖牌：不做實驗，直接去看操作手冊如何定義，像.append的定義就是：only modify the list have no return value printed – they return the default None  
* 接下來會介紹各種list的method，就去猜測 & 實戰看看  
* 再介紹其他list之前，想想功能性：如果我今天想要append東西到list的最後面，我有沒有別的作法？ 用R的邏輯，我就會寫c(list,x)，但在Python，我就會寫 list = list + [x]  








# NumPy  

## Why NumPy  

* 為啥要用NumPy呢? 其實簡單的理由就是，list無法做數學運算，他只能拿來存東西...  

```{python error = TRUE}
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight/(height**2)
```


* 因為list原本就是設計來存取資料的，它允許每個element可以是不同的type  
* 所以，即使你每個element都放float這種type，list還是list，不會變成numerical list  
* 所以你要叫list做數學運算時，他就不知道怎麼算了，畢竟他也不知道這個list是不是全都numerical的資訊  
* 而NumPy，就是numerical python的縮寫，他的np.array，就是numerical list，所以只要啟用numpy，就可以做計算了  


```{python}
import numpy as np
height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
weight/(height**2)
```

* 我們可以把np.array想成R的vector，如果你的array裡面放了不同type的東西，他會全部轉成string  

```{python}
np.array([1.0, "is", True])
```

* 所以，我們可以把對np.array所做的行為，想成在R裡面對vector所做的行為，而list的行為，都要往"儲存資料"的角度去想：  

```{python}
python_list = [1,2,3]
python_list + python_list
```

```{python}
numpy_array = np.array([1,2,3])
numpy_array + numpy_array
```

## Subset np.array  

* 也因為numpy可以做運算，所以在subset上，比list又更好用了  

```{python}
height_list = [1.73, 1.68, 1.71, 1.89, 1.79]
height_array = np.array([1.73, 1.68, 1.71, 1.89, 1.79])

height_list[1]
height_array[1]
```

```{python error = TRUE}
height_list[height_list>1.71]
```

```{python}
height_array[height_array>1.71]
```

## Statistics functions  

### Generate data  

```{python}
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))
np_city
```

### Summary statistics  

```{python}
# Print mean height (first column)
avg = np.mean(np_city[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_city[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_city[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_city[:,0], np_city[:,1])
print("Correlation: " + str(corr))
```



