# Function fundamentals









# map/filter/reduce with lambda function

## map with lambda

-   這邊要先介紹lambda function，也就是anonymus function。\
-   就是我們在使用map的時候，想要使用「用完即丟」的無名function，這個function就叫lambda function\
-   舉例來說，我有一個list，裡面每個element都是一個單詞，然後我想用map function去對此list的每個element做以下的運算：算單詞字長+2。那我就可以這樣寫：

```{python}
voc_list = ["Hank", "statistics", "basketball", "nice guy"]
result_map = map(lambda x: len(x)+2, voc_list)
print(result_map)
print(list(result_map))
```

-   從這個例子可以看到以下用法：

    -   `map`在python中，是先定義函數，再放iterable object進去。但在R裡面是倒過來，先給iterable object，才放自定義函數\
    -   自定義函數這邊，我們其實只想放個用完即丟的函數，不想先在外面定義好，才拿進來用。這時候，就會用到lambda function\
    -   這個lambda function的寫法，就是先宣告他是lambda function & 提供input parameter，加上冒號後，寫下function body就完成。所以他不用在一開始寫def，也不用在結束後寫return，省去很多麻煩。更重要的是，沒有額外在main script定義函數，所以減少了記憶體空間(因為不需要開個記憶體空間來存這個定義的函數)\
    -   map後的結果，是一個map object，要用`list()`把他轉成list，才看得到最後的結果

## filter with lambda

-   接下來講`filter`，他的寫法是這樣：`filter(lambda function, iterable)`，其中，這個lambda function的回傳值要是True/F alse，而filter的回傳值，就是把iterable所對應到的True給回傳出來\
-   所以很符合R的filter的用法：符合的，篩選出來\
-   看個例子：我想篩選出iterable中，字長+2後\>9的：

```{python}
print(voc_list)
result_filter = filter(lambda x: len(x)+2 > 9, voc_list)
print(list(result_filter))
```

-   接下來做個練習，剛剛的tweets data，有個column是text，如下：

```{python}
df['text']
```

-   其中，我覺得RT開頭的資訊對我來說蠻重要的，所以我想擷取出RT開頭的text。那這時就可以用到filter

```{python}
result = filter(lambda x: x[0:2]=="RT", df['text'])
res_list = list(result)
print(res_list[0:5])
```

## reduce with lambda

-   最後，講到reduce function\
-   他的作用直接舉例比較快： 我有一個list: [1,2,3,4,5]，我現在想要從最前面開始做兩個element的相加，也就是：1+2 = 3, 3+3 = 6, 6+4 = 10, 10+5 = 15\
-   那就可以用`reduce(lambda x, y: x+y, list)`\
-   小提醒是，reduce這個function住在functools這個package裡，所以要先import他：

```{python}
from functools import reduce
import numpy as np
num_list = [1,2,3,4,5]
result_reduce = reduce(lambda x, y: x+y, num_list)
print(result_reduce)
print(sum(num_list))
```


