# function101

## function的結構  

* function的 3+1 個part
  * function header: 這個function的名稱  
  * Docstrings: 開頭註解，用三引號夾起來，並照PEP8格式，寫下Purpose, Args, Returns, Raises這四個component (其中的Raises是指，什麼狀況下要給error)
  * function body: 這個function的內容  
  * output出什麼: 這是optional，你可以只做side-effect(e.g. 寫入資料庫)，但不output出東西。若要output出東西，可以output一個object(e.g. tuple)或ouptut出一個新的function(i.e. clousure，見`nested function`那章)  

* 以下是一個簡單但完整的function  

```{python}
def square(value): # <- Function header
  # <- Docstrings are below
  """
  Purpose: 
    Return the square of a value
  Args:
    value (int/float): the number to be squared
  Returns:
    int/float
  Raises:
    ValueError: If `value` is not int/float
  """
  
  # Function body
  if (not type(value) is int) and (not type(value) is float):
    raise TypeError("`value` must be the type of int/float")
  
  new_value = value**2 
  
  # output
  return new_value

```

## Docstring的標準格式  

* 從上例可以看到docstring的標準格式  
* 對開發者來說，他看到你的source code，就可以很清楚的知道function的目的, 參數, output, 以及什麼時候會給error  
* 對user來說，他雖然看不到你寫的註解，但他只要下help，就可以輕易看到這些內容：  

```{python}
help(square)
```

## 先檢驗argument的合法性    

* 此外，也可以看到比較professional的function寫法，會在一開始就檢驗你丟進來的arguments是否符合要求，不符合就報錯，來避免不必要的bug  
* 所以，我們測試一下就知道了：  

```{python error = TRUE}
print(square(3))
print(square(1.4))
print(square('haha'))
```

* 詳細的error handling寫法，會在下一個章節介紹  

## 記得`return`  

* 特別注意，如果要return value出來，最後一定要加`return`，不能像R偷懶，以為最後一行就會自己return出來  

## default argument  

* 這很easy拉，就簡單給個例子就好

```{python}
def power(number, pow = 1):
  """Raise number to the power of pow."""
  new_value = number ** pow
  return new_value

print(power(9, 2))
print(power(9))
```

* 要特別注意的是，default argument一定要放到最後面，不可以放到前面

